### ISSUE TITLE
Is there a Python version?

### ISSUE THREAD

**Issue by Cyclones-Y** [TensorStack-AI/OnnxStack#148]

**Comment by saddam213** [comment]
I think Diffusers would be the best option for python
https://github.com/huggingface/diffusers 

There would be no advantage to an OnnxStack python version as OnnxStack has significantly less features than the python libraries out there.

**Comment by YongBinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [comment]
is it possible to use the models you published on hugging face in python?

**Comment by saddam213** [comment]
> is it possible to use the models you published on hugging face in python?

Yes, these are ONNX conversions so are language agnostic , can be use anywhere, python, rust, c++

**Comment by YongBinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [comment]
> > is it possible to use the models you published on hugging face in python?
> 
> Yes, these are ONNX conversions so are language agnostic , can be use anywhere, python, rust, c++

I am new to those things.

I tried to use diffusers library to load your models but failed. 

Do you have any library recommendations?

**Comment by YongBinnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [comment]
> > is it possible to use the models you published on hugging face in python?
> 
> Yes, these are ONNX conversions so are language agnostic , can be use anywhere, python, rust, c++

I am new to those things.

I tried to use diffusers library to load your models but failed. 

Do you have any library recommendations?

**Comment by saddam213** [comment]
> > > is it possible to use the models you published on hugging face in python?
> > 
> > 
> > Yes, these are ONNX conversions so are language agnostic , can be use anywhere, python, rust, c++
> 
> I am new to those things.
> 
> I tried to use diffusers library to load your models but failed.
> 
> Do you have any library recommendations?

Unfortunately I don't know the python language so don't know the libraries that can be used
